[theme]
base = "dark"
primaryColor = "#6C7DFF"
backgroundColor = "#0d4a4a"
secondaryBackgroundColor = "#072B2D"
textColor = "#f4f6ff"
font = "sans serif"

[client]
toolbarMode = "minimal"
showErrorDetails = false

[browser]
gatherUsageStats = false