[theme]
base = "dark"
primaryColor = "#6C7DFF"
backgroundColor = "#050514"
secondaryBackgroundColor = "#0B0C23"
textColor = "#f4f6ff"
font = "sans serif"

[client]
toolbarMode = "minimal"
showErrorDetails = false

[browser]
gatherUsageStats = false
